<a href="https://colab.research.google.com/github/saisumedha/FMML-PROJECTS_AND_LABS/blob/main/LAB1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**`Section 1 - Python : Basic data types and indexing.`**

QUESTION 0

In [6]:
# list datatype
#append()
List = []
List.append('sa')
List.append(3)
List.append('2.3')
print(List)

['sa', 3, '2.3']


In [7]:
#extend()
List1 = ['books',54,'s']
List2 = ['1.2','my hobby']
List1.extend(List2)
print(List1)

['books', 54, 's', '1.2', 'my hobby']


In [8]:
#reverse()
List = ['you','see','I']
List.reverse()
print(List)

['I', 'see', 'you']


In [10]:
#string
#upper
string = "how do you do"
uppercase_string = string.upper()
print(uppercase_string)

HOW DO YOU DO


In [11]:
#lower
string = "how do you do"
lowercase_string = string.lower()
print(lowercase_string)

how do you do


In [13]:
#split
string = "roses,berries,cakes"
splited_list = string.split(',')
print(splited_list)

['roses', 'berries', 'cakes']


In [16]:
#sets
#add
Set = set()
Set.add(45)
Set.add(0)
Set.add(9)
print(Set)

{0, 9, 45}


In [17]:
# update
set1 = {1, 2, 3}
set2 = {3, 4, 5}
set1.update(set2)
print(set1)

{1, 2, 3, 4, 5}


In [18]:
#remove
set = {23,45,45,12}
set.remove(45)
print(set)

{12, 23}


QUESTION 1

In [19]:
def reverse_and_append(A, B):
    reversed_A = A[::-1] # Reverse the first string A using slicing
    result = B + reversed_A
    return result

string_A = "Hello"
string_B = "World"
final_string = reverse_and_append(string_A, string_B)
print(final_string)


WorldolleH


QUESTION 2

In [21]:
def find_highest_female_worker(work_hours):
    max_hours = 0
    female_name = ''

    for name, hours, gender in work_hours:
        if gender == 'F' and hours > max_hours:
            max_hours = hours
            female_name = name
    if female_name:
        female_pay = max_hours * 20
        print(f"female worker who worked the most hours is {female_name}")
        print(f"She should be paid ${female_pay}")
    else:
        print("No female workers found in the list.")
work_hours = [('Abby', 100, 'F'), ('Billy', 400, 'M'), ('Cassie', 800, 'F'), ('Maggi', 600, 'F'),
              ('Alex', 500, 'M'), ('Raj', 225, 'M'), ('Penny', 920, 'F'), ('Ben', 300, 'M')]
find_highest_female_worker(work_hours)

female worker who worked the most hours is Penny
She should be paid $18400


QUESTION 3

In [29]:
import numpy as np
A = np.array([[1,1,1,1,1],[2,2,2,2,2]])
B = np.array([[3,3,3,3,3],[4,4,4,4,4],[5,5,5,5,5]])
C = np.vstack((A,B))
print(C)

[[1 1 1 1 1]
 [2 2 2 2 2]
 [3 3 3 3 3]
 [4 4 4 4 4]
 [5 5 5 5 5]]


In [30]:
other_matrix = np.random.randint(1, 10, (5, 5))
# Finding the dot product
dot_product_result = np.dot(C, other_matrix)
print("\nDot Product Matrix:")
print(dot_product_result)


Dot Product Matrix:
[[ 24  20  27  29  26]
 [ 48  40  54  58  52]
 [ 72  60  81  87  78]
 [ 96  80 108 116 104]
 [120 100 135 145 130]]
